remote: true

experienceLevel:
  internship: false
  entry: true
  associate: true
  mid-senior level: true
  director: false
  executive: false

jobTypes:
  full-time: true
  contract: true
  part-time: false
  temporary: false
  internship: false
  other: false
  volunteer: false

date:
  all time: false
  month: false
  week: true
  24 hours: true

positions:
  - Product Manager
  - Product Owner
  - Technical Product Manager
  - Project Manager
  - Program Manager
  - Technical Program Manager

locations:
  - United States

apply_once_at_company: true

distance: 500

company_blacklist:
  - Google
  - Amazon

title_blacklist:
  - Sales
  - Marketing
  - Trainee

location_blacklist:
  - Brazil
  - Mexico
  - London
  - Germany
  - India

job_applicants_threshold:
  min_applicants: 0
  max_applicants: 50

llm_model_type: openai
llm_model: 'gpt-4o-mini'
llm_api_url: 'https://api.pawan.krd/cosmosrp/v1'
